### ISSUE TITLE
As a developper, I want to access the data via an API

### ISSUE THREAD

**Issue by WindOfRussia** [alexstojda/SOEN341#94]
[Priority: Medium, Risk:Low]

For AJAX to work, with or without view, we need to implement all our data output in a RESTful API format, feeding JSON via endpoints allowing for quick, seamless and dynamic UI.

Acceptance Test : 
- [x] I can access comments data via the /api/comments endpoints
- [x] I can access questions data via the /api/questions endpoints
- [x] I can access answers data via the /api/answers endpoints
- [x] I can access votes data via the /api/{type}/{id}/votes endpoint (included in #64)
